31/clear chat
graasp/graasp-chatbox pull request #34
Opened 2022-04-19 15:22 UTC by spaenleh

This PR adds admin tools to clear chat (displayed to admins).

Admin tools:
<img width="405" alt="Screenshot 2022-04-19 at 17 20 51" src="https://user-images.githubusercontent.com/39373170/164038579-4a666453-102f-48ee-80ce-ab9777116564.png">

Confirm dialog:
<img width="682" alt="Screenshot 2022-04-19 at 17 20 40" src="https://user-images.githubusercontent.com/39373170/164038492-cd106e86-f501-4afa-98aa-ccf1f7b74e5e.png">

closes #31

2022-04-21 14:07 UTC, pyphilia requested changes
🐑

2022-04-21 14:07 UTC, pyphilia commented on src/test/admin-tools.test.tsx
> +        console.log('filename:', filename);
remove

2022-04-21 14:07 UTC, pyphilia commented on src/test/admin-tools.test.tsx
> +    const clearChatSpy = spyMethod('spyMethod');
Maybe give it a better name.

2022-04-21 14:07 UTC, pyphilia commented on src/test/utils/utils.ts
> +  console.log(data);
Remove.

2022-04-25 07:10 UTC, spaenleh commented
Here is an updated screenshot of the dialog that opens before clearing the chat, with an added button to save the chat:
<img width="627" alt="Screenshot 2022-04-22 at 18 24 33" src="https://user-images.githubusercontent.com/39373170/165038133-7b839317-dda8-4d8e-ab06-6b4d978d68e2.png">

2022-04-26 12:46 UTC, pyphilia approved these changes
🦒

2022-04-26 12:46 UTC, pyphilia commented on src/components/ClearChat.tsx
> +            <ExportChat variant="button" text="Save Chat" />
Translate save chat?

2022-04-26 14:45 UTC, merged